version: '2'
services:
  nginx:
    depends_on:
     - php
    image: nginx:latest
    expose:
     - 80
     - 443
    ports:
     - "80:80"
    links:
     - php:php
     - php7.2:php7.2
    volumes:
     - /home/mxc/lnmp/www:/usr/share/nginx/html
     - /home/mxc/lnmp/nginx/conf.d:/etc/nginx/conf.d
  php:
    build: ./php
    depends_on:
      - mysql
      - redis
#    image: php:7.1.0-fpm  # see below
    expose:
      - 9000
    ports:
      - "9001:9000"
    volumes:
      - /home/mxc/lnmp/www/:/var/www/html/
      - /home/mxc/lnmp/php/etc/:/usr/local/etc/
#      - /home/mxc/lnmp/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    links:
      - mysql:mysql
      - redis:redis
      - mongo:mongo
      - rabbitmq:rabbitmq
#    commands:

    environment:
      MYSQL_HOST: mysql:3306
      REDIS_HOST: redis:6379
      MONGO_HOST: mongo:27017
    php7.2:
    build: ./php/php7.2
    depends_on:
      - mysql
      - redis
      - rabbitmq
#    image: php:7.1.0-fpm  # see below
    expose:
      - 9000
    ports:
      - "9002:9002"
    volumes:
      - /home/mxc/lnmp/www/:/var/www/html/
      # - /home/mxc/lnmp/php/php7.2-etc/:/usr/local/etc/
      # - /home/mxc/lnmp/php/conf.d:/usr/local/etc/php/conf.d
    links:
      - mysql:mysql
      - redis:redis
      - rabbitmq:rabbitmq
    environment:
      MYSQL_HOST: mysql:3306
      REDIS_HOST: redis:6379
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - /home/mxc/lnmp/mysql/data:/var/lib/mysql
        - /home/mxc/lnmp/mysql/config:/etc/mysql/conf.d
    expose:
      - 3306
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.7.2-management
    expose:
      - 5672
      - 15672
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
#     RABBITMQ_DEFAULT_VHOST: /
